### ISSUE TITLE
The truth value of an array with more than one element is ambiguous.

### ISSUE THREAD

**Issue by nanxintin** [alibaba/gym-starcraft#2]
When running the example,  I came across an error:
"""
Traceback (most recent call last):
  File "random_agent.py", line 30, in <module>
    obs, reward, done, info = env.step(action)
  File "/Library/Python/2.7/site-packages/gym/core.py", line 122, in step
    observation, reward, done, info = self._step(action)
  File "/Users/sk/Projects/gym-starcraft/gym_starcraft/envs/starcraft_env.py", line 36, in _step
    self.client.send(self._make_commands(action))
  File "/Users/sk/Projects/gym-starcraft/gym_starcraft/envs/single_battle_env.py", line 33, in _make_commands
    if self.state is None or not action:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
"""
It seems there is a problem with the gym environment and the starcraft, but I can't solve it.
I would appreciate it if someone could help me.

**Comment by tkipf** [comment]
Same issue here. Installed gym-0.9.1 via pip and otherwise followed the installation instructions for both torchcraft-py and gym-starcraft.

**Comment by tkipf** [comment]
Replacing line 33 in `gym_starcraft/envs/single_battle_env.py` with:
```
        if self.state is None or action is None:
```
should do the trick.

**Comment by nanxintin** [comment]
@tkipf  Thanks a lot. It really works.
